name: 定时构建

on:
  schedule:
    - cron: '*/40 * * * *'  # 每40分钟执行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Git 用户信息
        run: |
          git config --global user.name "$(git hub --user)"
          git config --global user.email "$(git hub --email)"

      - name: 安装 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 安装依赖
        run: npm install

      - name: 启动应用程序
        run: npm start
